// Code Generated by Sidekick is for learning and experimentation purposes only.
export class HandlerRegistry<H extends Record<string, (payload: any) => any>> {
  private handlers: Partial<H> = {};

  register<K extends keyof H>(name: K, handler: H[K]) {
    this.handlers[name] = handler;
  }

  get<K extends keyof H>(name: K): H[K] | undefined {
    return this.handlers[name];
  }
}
